# SPDX-FileCopyrightText: Copyright (c) 2016-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
AllCops:
  Exclude:
    - 'bin/**/*'
    - 'assets/**/*'
    - 'vendor/**/*'
  DisplayCopNames: true
  TargetRubyVersion: 2.6.0
  NewCops: enable
  SuggestExtensions: false
plugins:
  - rubocop-rake
  - rubocop-minitest
  - rubocop-performance
Layout/MultilineOperationIndentation:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Naming/MethodParameterName:
  MinNameLength: 1
Style/CommandLiteral:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/IndentationWidth:
  Enabled: false
Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false
Layout/ElseAlignment:
  Enabled: false
Layout/EndAlignment:
  Enabled: false
Lint/RescueException:
  Enabled: false
Metrics/MethodLength:
  Max: 50
Metrics/ClassLength:
  Max: 200
  Exclude:
    - "test/test_*.rb"
Metrics/AbcSize:
  Max: 60
Metrics/BlockLength:
  Max: 100
Layout/MultilineMethodCallIndentation:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 11
Metrics/PerceivedComplexity:
  Max: 11
Layout/LineLength:
  Max: 120
Style/OpenStructUse:
  Enabled: false
Style/ComparableClamp:
  Enabled: false
