AllCops:
  Exclude:
    - 'bin/**/*'
    - 'assets/**/*'
  DisplayCopNames: true

Naming/UncommunicativeMethodParamName:
  MinNameLength: 1
Style/CommandLiteral:
  Enabled: false
Layout/IndentationWidth:
  Enabled: false
Layout/ElseAlignment:
  Enabled: false
Layout/EndAlignment:
  Enabled: false
Lint/RescueException:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/MethodLength:
  Max: 50
Metrics/ClassLength:
  Max: 200
Metrics/AbcSize:
  Max: 60
Metrics/BlockLength:
  Max: 100
Layout/MultilineMethodCallIndentation:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10
