docker:
  image: yegor256/rultor-image:1.9.0
# readers:
#   - "urn:github:526301"
assets:
  config.yml: yegor256/home#assets/0pdd/config.yml
  id_rsa: yegor256/home#assets/heroku-key
  id_rsa.pub: yegor256/home#assets/heroku-key.pub
install: |-
  git config --global user.email "server@0pdd.com"
  git config --global user.name "0pdd.com"
  sudo gem install pdd
  pdd -f /dev/null
  sudo gem install bundler
  sudo bundle install --no-color "--gemfile=$(pwd)/Gemfile"
release:
  sensitive:
    - config.yml
  script: |-
    bundle exec rake
    git remote add dokku dokku@dokku.0pdd.com:zeropdd
    rm -rf ~/.ssh
    mkdir ~/.ssh
    mv ../id_rsa ../id_rsa.pub ~/.ssh
    chmod -R 600 ~/.ssh/*
    echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null" > ~/.ssh/config
    git fetch
    sed -i "s/BUILD/${tag}/g" ./version.rb
    git add ./version.rb
    git commit -m 'build number set'
    cp ../config.yml config.yml
    git add config.yml
    bundle exec ruby test/test_credentials.rb
    git commit -m 'config.yml'
    git push -f dokku $(git symbolic-ref --short HEAD):master
    git reset HEAD~1
    rm -rf config.yml
    curl -f --connect-timeout 15 -k --retry 5 --retry-delay 30 https://www.0pdd.com > /dev/null
merge:
  script: |-
    bundle exec rake
