POST http://localhost:4567/hook/github
content-type: application/json

{
  "ref": "refs/heads/main",
  "before": "2098c6a633c6668ed583810ebb5db02c80449821",
  "after": "2655c13f79adb817f713dd878c50eb06ee3d9a04",
  "repository": {
    "id": 349524779,
    "node_id": "MDEwOlJlcG9zaXRvcnkzNDk1MjQ3Nzk=",
    "name": "react-starter",
    "full_name": "mbao01/react-starter",
    "private": true,
    "owner": {
      "name": "mbao01",
      "email": "mbao01@users.noreply.github.com",
      "login": "mbao01",
      "id": 10655408,
      "node_id": "MDQ6VXNlcjEwNjU1NDA4",
      "avatar_url": "https://avatars.githubusercontent.com/u/10655408?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mbao01",
      "html_url": "https://github.com/mbao01",
      "followers_url": "https://api.github.com/users/mbao01/followers",
      "following_url": "https://api.github.com/users/mbao01/following{/other_user}",
      "gists_url": "https://api.github.com/users/mbao01/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mbao01/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mbao01/subscriptions",
      "organizations_url": "https://api.github.com/users/mbao01/orgs",
      "repos_url": "https://api.github.com/users/mbao01/repos",
      "events_url": "https://api.github.com/users/mbao01/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mbao01/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/mbao01/react-starter",
    "description": "Starter for react projects",
    "fork": false,
    "url": "https://github.com/mbao01/react-starter",
    "forks_url": "https://api.github.com/repos/mbao01/react-starter/forks",
    "keys_url": "https://api.github.com/repos/mbao01/react-starter/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/mbao01/react-starter/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/mbao01/react-starter/teams",
    "hooks_url": "https://api.github.com/repos/mbao01/react-starter/hooks",
    "issue_events_url": "https://api.github.com/repos/mbao01/react-starter/issues/events{/number}",
    "events_url": "https://api.github.com/repos/mbao01/react-starter/events",
    "assignees_url": "https://api.github.com/repos/mbao01/react-starter/assignees{/user}",
    "branches_url": "https://api.github.com/repos/mbao01/react-starter/branches{/branch}",
    "tags_url": "https://api.github.com/repos/mbao01/react-starter/tags",
    "blobs_url": "https://api.github.com/repos/mbao01/react-starter/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/mbao01/react-starter/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/mbao01/react-starter/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/mbao01/react-starter/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/mbao01/react-starter/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/mbao01/react-starter/languages",
    "stargazers_url": "https://api.github.com/repos/mbao01/react-starter/stargazers",
    "contributors_url": "https://api.github.com/repos/mbao01/react-starter/contributors",
    "subscribers_url": "https://api.github.com/repos/mbao01/react-starter/subscribers",
    "subscription_url": "https://api.github.com/repos/mbao01/react-starter/subscription",
    "commits_url": "https://api.github.com/repos/mbao01/react-starter/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/mbao01/react-starter/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/mbao01/react-starter/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/mbao01/react-starter/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/mbao01/react-starter/contents/{+path}",
    "compare_url": "https://api.github.com/repos/mbao01/react-starter/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/mbao01/react-starter/merges",
    "archive_url": "https://api.github.com/repos/mbao01/react-starter/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/mbao01/react-starter/downloads",
    "issues_url": "https://api.github.com/repos/mbao01/react-starter/issues{/number}",
    "pulls_url": "https://api.github.com/repos/mbao01/react-starter/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/mbao01/react-starter/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/mbao01/react-starter/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/mbao01/react-starter/labels{/name}",
    "releases_url": "https://api.github.com/repos/mbao01/react-starter/releases{/id}",
    "deployments_url": "https://api.github.com/repos/mbao01/react-starter/deployments",
    "created_at": 1616179714,
    "updated_at": "2022-01-06T14:12:17Z",
    "pushed_at": 1642152669,
    "git_url": "git://github.com/mbao01/react-starter.git",
    "ssh_url": "git@github.com:mbao01/react-starter.git",
    "clone_url": "https://github.com/mbao01/react-starter.git",
    "svn_url": "https://github.com/mbao01/react-starter",
    "homepage": null,
    "size": 264,
    "stargazers_count": 2,
    "watchers_count": 2,
    "language": "TypeScript",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 8,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "topics": [

    ],
    "visibility": "private",
    "forks": 0,
    "open_issues": 8,
    "watchers": 2,
    "default_branch": "main",
    "stargazers": 2,
    "master_branch": "main"
  },
  "pusher": {
    "name": "mbao01",
    "email": "mbao01@users.noreply.github.com"
  },
  "sender": {
    "login": "mbao01",
    "id": 10655408,
    "node_id": "MDQ6VXNlcjEwNjU1NDA4",
    "avatar_url": "https://avatars.githubusercontent.com/u/10655408?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/mbao01",
    "html_url": "https://github.com/mbao01",
    "followers_url": "https://api.github.com/users/mbao01/followers",
    "following_url": "https://api.github.com/users/mbao01/following{/other_user}",
    "gists_url": "https://api.github.com/users/mbao01/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/mbao01/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/mbao01/subscriptions",
    "organizations_url": "https://api.github.com/users/mbao01/orgs",
    "repos_url": "https://api.github.com/users/mbao01/repos",
    "events_url": "https://api.github.com/users/mbao01/events{/privacy}",
    "received_events_url": "https://api.github.com/users/mbao01/received_events",
    "type": "User",
    "site_admin": false
  },
  "created": false,
  "deleted": false,
  "forced": false,
  "base_ref": null,
  "compare": "https://github.com/mbao01/react-starter/compare/2098c6a633c6...2655c13f79ad",
  "commits": [
    {
      "id": "2655c13f79adb817f713dd878c50eb06ee3d9a04",
      "tree_id": "bf08093ea12acb1c56aa6a879b1c45648ab7bf80",
      "distinct": true,
      "message": "Another critical update",
      "timestamp": "2022-01-14T10:31:09+01:00",
      "url": "https://github.com/mbao01/react-starter/commit/2655c13f79adb817f713dd878c50eb06ee3d9a04",
      "author": {
        "name": "Ayomide Bakare",
        "email": "mbao01@users.noreply.github.com",
        "username": "mbao01"
      },
      "committer": {
        "name": "GitHub",
        "email": "noreply@github.com",
        "username": "web-flow"
      },
      "added": [

      ],
      "removed": [

      ],
      "modified": [
        "src/setupTests.ts"
      ]
    }
  ],
  "head_commit": {
    "id": "2655c13f79adb817f713dd878c50eb06ee3d9a04",
    "tree_id": "bf08093ea12acb1c56aa6a879b1c45648ab7bf80",
    "distinct": true,
    "message": "Another critical update",
    "timestamp": "2022-01-14T10:31:09+01:00",
    "url": "https://github.com/mbao01/react-starter/commit/2655c13f79adb817f713dd878c50eb06ee3d9a04",
    "author": {
      "name": "Ayomide Bakare",
      "email": "mbao01@users.noreply.github.com",
      "username": "mbao01"
    },
    "committer": {
      "name": "GitHub",
      "email": "noreply@github.com",
      "username": "web-flow"
    },
    "added": [

    ],
    "removed": [

    ],
    "modified": [
      "src/setupTests.ts"
    ]
  }
}

###

POST http://localhost:4567/hook/gitlab
content-type: application/json

{
  "object_kind": "push",
  "event_name": "push",
  "before": "8ec123c6b39fcac8ab88667b85900778f8f53dfc",
  "after": "0e9dfe56fe53c9faccbb3ba75c52028c727fddc0",
  "ref": "refs/heads/master",
  "checkout_sha": "0e9dfe56fe53c9faccbb3ba75c52028c727fddc0",
  "message": null,
  "user_id": 1400220,
  "user_name": "Ayomide Bakare",
  "user_username": "mbao01",
  "user_email": "",
  "user_avatar": "https://secure.gravatar.com/avatar/bc8ecfeba90cd39278dc449bef3151d9?s=80&d=identicon",
  "project_id": 7963908,
  "project": {
    "id": 7963908,
    "name": "ayomidebakare.com",
    "description": "",
    "web_url": "https://gitlab.com/mbao01/ayomidebakare.com",
    "avatar_url": null,
    "git_ssh_url": "git@gitlab.com:mbao01/ayomidebakare.com.git",
    "git_http_url": "https://gitlab.com/mbao01/ayomidebakare.com.git",
    "namespace": "Ayomide Bakare",
    "visibility_level": 20,
    "path_with_namespace": "mbao01/ayomidebakare.com",
    "default_branch": "master",
    "ci_config_path": null,
    "homepage": "https://gitlab.com/mbao01/ayomidebakare.com",
    "url": "git@gitlab.com:mbao01/ayomidebakare.com.git",
    "ssh_url": "git@gitlab.com:mbao01/ayomidebakare.com.git",
    "http_url": "https://gitlab.com/mbao01/ayomidebakare.com.git"
  },
  "commits": [
    {
      "id": "0e9dfe56fe53c9faccbb3ba75c52028c727fddc0",
      "message": "Update .pdd, src/App.js",
      "title": "Update .pdd, src/App.js",
      "timestamp": "2022-01-06T16:36:26+00:00",
      "url": "https://gitlab.com/mbao01/ayomidebakare.com/-/commit/0e9dfe56fe53c9faccbb3ba75c52028c727fddc0",
      "author": {
        "name": "Ayomide Bakare",
        "email": "bakkareayomideo@gmail.com"
      },
      "added": [
        ".pdd"
      ],
      "modified": [
        "src/App.js"
      ],
      "removed": []
    }
  ],
  "total_commits_count": 1,
  "push_options": {},
  "repository": {
    "name": "ayomidebakare.com",
    "url": "git@gitlab.com:mbao01/ayomidebakare.com.git",
    "description": "",
    "homepage": "https://gitlab.com/mbao01/ayomidebakare.com",
    "git_http_url": "https://gitlab.com/mbao01/ayomidebakare.com.git",
    "git_ssh_url": "git@gitlab.com:mbao01/ayomidebakare.com.git",
    "visibility_level": 20
  }
}

###

GET http://localhost:4567/xml?name=mbao01/ayomidebakare.com
content-type: text/xml
