# SPDX-FileCopyrightText: Copyright (c) 2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT

version = 1
[[annotations]]
path = [
    "**.json",
    "**.md",
    "**.png",
    "**.sigil",
    "**.svg",
    "**.txt",
    "**/*.csv",
    "**/*.jpg",
    "**/*.json",
    "**/*.md",
    "**/*.pdf",
    "**/*.png",
    "**/*.svg",
    "**/*.txt",
    "**/*.vm",
    "**/.DS_Store",
    "**/.gitignore",
    "**/.pdd",
    "**/CNAME",
    "**/Gemfile.lock",
    "**/Procfile",
    ".DS_Store",
    ".gitattributes",
    ".gitignore",
    ".pdd",
    "Aptfile",
    "Gemfile.lock",
    "Procfile",
    "README.md",
    "doc/integration.puml",
    "nginx.conf.sigil",
    "renovate.json",
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (c) 2025 Yegor Bugayenko"
SPDX-License-Identifier = "MIT"
